#가본 계산기
def add(a,b):
    return a+b;
def subtract(a,b):
    return a-b;
def divide_new(a,b):
    return a/b;
def mutiply(a,c):
    return a*c;
def complex(a,b,c):
    return a*b+c;
def say_hello():
    print("hello world");
